#!/bin/csh -f

# Attempt to beautify/deuglify the godawful raw Starlab install log.
#
# Targets to improve/remove:
#
# ^if /bin/sh ...\
# ^then ...
#
# ^mkdir .libs
#
# ^if g++ ... \
# ^then ...

set which = 2			# hardcoded

set in = install.log
if ($#argv > 0) set in = $1

if ($which == 1) then

    # Version 1: insert space before each compile/link command.

    sed 's/^if \/bin\/sh/\n\nif \/bin\/sh/;s/^mkdir .libs/\n\nmkdir .libs/;s/^if g++/\n\nif g++/' $in >! $in.2

else

    # Version 2: remove "setup" commands; insert space before "real" commands.

    sed '/^if \/bin\/sh/d;/^then /d;s/^mkdir .libs/\n\nmkdir .libs/;/^if g++/d;s/^gcc/\n\ngcc/;s/^g++/\n\ng++/;s/^ gcc/\n\ngcc/;s/^ g++/\n\ng++/;s/\/bin\/sh /\n\/bin\/sh /' $in >! $in.2

endif



