#!/bin/csh -f

if ($#argv < 2) then
  /bin/ls -F $argv[*]
else
  @ first_file = $#argv
  @ i = 1
  while ($i <= $#argv)
    if (-e $argv[$i]) then
        @ first_file = $i
        break
    endif
    @ i++
  end
  if ($first_file == $#argv) then
    /bin/ls -F $argv[*]
  else
    /bin/ls -d -F $argv[*]
  endif
endif
