#!/bin/sh
#
# Starlab make helper.
#
# Given a list of object files, create zero-length source files (type
# extension given by the first argument) if none exists.
#
if [ $# -lt 1 ]; then
  echo "Usage: $0 .suffix  file.o ...
Given a list of object files, create zero-length source files
(type extension given by first argument) if none exists." >&2
  exit 1
fi
#
suf="$1"
shift
for file in "$@"; do
    src=`expr match "$file" '\(.*\)\.o$'`$suf
    if [ ! -f "$src" ]; then
	touch "$src"
    fi
done
