#!/bin/tcsh -f
# (tcsh necessary with Redhat Linux, v. 4.x...)
#
# Starlab make helper.
#
# Compile a C++ source file $1 iff it is non-null.
# Other arguments give compile command, switches, etc.
#
# NOTE: It might be best to make this a Bourne-shell script, for
#       the sake of efficiency.
#
if ($#argv < 2) exit
#
set src = $1
#
set temp = (`wc $src`)
if ($temp[1] == 0) then
    touch $1
else
    set date = `date +%a_%b_%d_%Y,_%T_%Z`
    alias comp $argv[2*]

    echo $argv[2*] -c $1 -D_COMPILE_DATE_=\"$date\"
    comp           -c $1 -D_COMPILE_DATE_=\"$date\"

#   (Doesn't seem to be easy to combine these repeated arguments
#    into a single string...)

endif	
