#!/bin/sh
#
# Starlab make helper.
#
# Prepend the current directory (relative to STARLAB_PATH) onto the
# specified files, and print them out.  For use with "make tarlist".
#
if [ $# = 0 ]; then
  echo "Usage: $0 file ...
given a list of filenames relative to \".\",
emit corresponding list relative to \$STARLAB_PATH ($STARLAB_PATH)" >&2
  exit 1
fi

#
# Determine where we are...
#
pwd=`pwd`
local_path=`expr match "$pwd/" ".*/\($STARLAB_VERSION/.*\)"`
for file in "$@"; do
    echo "$local_path$file "
done
