#!/bin/sh
#
# makewalk:  Descend into specified directories to perform the
#	     requested make.
#
name=`basename $0`
#
pwd=`pwd`
target="$1"
shift
for dirname in "$@"; do
    if [ -d $pwd/$dirname ]; then
	cd $pwd/$dirname
	case "$0" in
	  *makewalk.quiet) ;;
	  *)
	    echo "==> descending to $pwd/$dirname,"
	    echo "      to execute  \"${MAKE:-make} $STARLAB_MAKEFLAGS $target\""
	    ;;
	esac
	${MAKE:-make} $STARLAB_MAKEFLAGS $target
	cd $pwd
    else
	:
#
#	Silently ignore missing directories.
#
#	echo '==>' No directory $pwd/$dirname
    fi
done
