#!/bin/tcsh -f
# (tcsh necessary with Redhat Linux, v. 4.x...)
#
# Starlab make helper.
#
# Given a list of object files, create zero-length source files (type
# extension given by the first argument) if none exists.
#
if ($#argv < 2) exit
#
foreach file ($argv[2*])
    set temp = $file:r
    if (! -e $temp$1) touch $temp$1
end
