#!/bin/tcsh -f
# (tcsh necessary with Redhat Linux, v. 4.x...)
#
# makewalk:  Descend into specified directories to perform the
#	     requested make.
#
set full_name = $0
set name = $full_name:t
#
foreach dirname ($argv[2*])
    if (-d $dirname) then
	set olddir = $cwd
	cd $dirname

	set flag = " "
	if ($?STARLAB_MAKEFLAGS) then
	    set flag = "$STARLAB_MAKEFLAGS"
	endif
	if (X$name != Xmakewalk.quiet) then
	    echo '==>' descending to $cwd,
	    echo '      'to execute' ' \"make $flag $1\"
	endif
	make $flag $1
	cd $olddir
    else
#
#	Silently ignore missing directories.
#
#	echo '==>' No directory $dirname
    endif
end
