LDFLAGS = -lm
EXECUTABLES = check_dep earliest_time latest_time sqrt # strings trn

all:	$(EXECUTABLES)

hide_exe:
	@./hide $(EXECUTABLES)

show_exe:
	@./show $(EXECUTABLES)

clean:
	@/bin/rm -f $(EXECUTABLES)
