#!/bin/sh

# Install (do not build) the specified files by copying them to the
# proper directory.

if [ $# -lt 1 ]; then
    echo "$0: At least one argument required." >&2
    exit 1
fi

if [ "x$STARLAB_INSTALL_PATH" == "x" ]; then
    echo STARLAB_INSTALL_PATH not set
    exit 1
fi

while [ "x$1" != "x" ]; do
    echo Installing $1 in $STARLAB_INSTALL_PATH
    cp -p $1 $STARLAB_INSTALL_PATH/bin
    shift
done

