#!/usr/local/bin/tcsh -f

if ($#argv < 1) exit

set tmp = $1
set ext = $tmp:e

alias CAT cat
if (X$ext == XZ) then
    alias CAT 'uncompress -c'
else if (X$ext == Xgz) then
    alias CAT 'gunzip -c'
endif

# "grep -A" version is quicker, but option doesn't exist in every UNIX.

#CAT $* | grep -A 1 'selected percentiles' \
CAT $* \
    | awk -f $STARLAB_PATH/sbin/lagr.awk \
    | plot_data -q -x 'log #' -y 'Lagrangian radii' -c 1 2 3 4 5 6 7 8 9 10 \
    		-C red red red red green blue \
		-h "Data from $*"
