#!/bin/sh

if [ $# = 0 ]; then
  exit 1
fi

case "$1" in
  *gz) CAT="gunzip -c" ;;
  *Z)  CAT="uncompress -c" ;;
  *)   CAT="cat" ;;
esac

$CAT "$@" | grep 'd(d' \
    | awk '{print ++i, $3;}' \
    | plot_data -q -x 'log #' -y de -C red \
		-h "Data from $*"
