#!/bin/sh

if [ $# = 0 ]; then
  
case "$1" in
  *gz) CAT="gunzip -c" ;;
  *Z)  CAT="uncompress -c" ;;
  *) CAT="cat" ;;
esac

$CAT "$@" | egrep 'Time =|rcore =' \
    | awk '{if ($1 == "Time") t = $3; if ($1 == "rcore") print t, $3;}' \
    | plot_data -q -x t -y rcore -C red \
		-h "Data from $*"
