#!/usr/local/bin/tcsh -f

if ($#argv < 1) exit

set tmp = $1
set ext = $tmp:e

alias CAT cat
if (X$ext == XZ) then
    alias CAT 'uncompress -c'
else if (X$ext == Xgz) then
    alias CAT 'gunzip -c'
endif

CAT $* | grep 'd(d' \
    | awk '{print ++i, $6;}' \
    | plot_data -q -x 'log #' -y 'd(de)' -C red \
		-h "Data from $*"
