#!/bin/tcsh

# Make a standard Plummer model with 100 stars and 25% binaries, then
# integrate it for 5 crossing times.  All other parameter choices are
# made automatically.  Standard units are used; all binary energies are
# 5 kT, eccentricities are thermal.
#
# The resulting model is written to stdout.

# Defaults:

set N = 50
set seed = 12345
set fb = 0.1
set eb = 5

makeplummer -n $N -s $seed -i \
	| makesecondary -i -f $fb \
	| scale -s \
	| makebinary -l $eb -u $eb -s $seed \
	| kira -t 5 -d 5 -D 0
