#!/bin/csh -f
#
set seed = " "
if ($#argv > 0) then
    set seed = "-s $1"
endif
mkplummer -i -o -n 5 $seed | flat_hermite -e .01 -t 1000 -d 10 -D .05 -C 4 | make_tree -k 2 | xstarplot -s 1.4 -l 4 -t
